Vue.component("news-ticker", {
    data: function()
    {
        return {
            messages: [
                "Im Functions Master",
                "Vk4gV1ZXTFhWVyBGTEI=",
                "update TNT already bro",
                "Cookie",
                "epic fail",
                "OLEZ EZ EZ EZ EZ EZ EZ EZ EZ EZ EZ EZ ...",
                "Welcome to the OLEZ, Hope you enjoy your <strike>stay</strike> pain!",
                "There's no secrets in the news im sure",
                "This game takes more than 5 hours, trust me",
                "This game takes exactly 5 hours, trust me",
                "This game takes less than 5 hours, trust me",
                "You Expected a News Ticker but it was me, dio!",
                "Imagine Failing at Fixing NaN",
                "you just got news ticker'd share this to anyone to get un-news ticker'd",
                "Before we begin the video, this mod is sponsored by RAID: Shadow Legends",
                "This is so Unfunity",
                "@every1 - yourself",
                "Get NaN'd lol",
                "i love this engine",
                "Thanks jwklong for omega engine",
                "Time to run away",
                "Update when?",
                "Can you see me?",
                "Keep Pinging Jeehan, Trust me",
                "Hello, your save just broke.",
                "#SaveFunctions",
                "Not Knot",
                "wengine",
                "There's a hidden message in some news ticker",
                "when the game is easier",
                "Omega Layers EZ+ is coming. - JeehanMoment",
                "Omega Layers EZ EZ is coming. - JeehanMoment",
                "Omega Layers Mods in 3007 be like: Sussy Never Layers EX EZ NG+ VIP (Functions Master Edition) V1.896 now has over 12321 layers, 356784 achievements and over 65536 news tickers, they decided to hire more modders for the cool",
                "🚓 🚓",
                "Don't read me.",
                "This is some ng+ stuffs going on",
                "Stop Clicking Me!",
                "There's alot of free achievements.",
                "Aleph-Null",
                "Jeesus Christ.",
                "Hah you looked",
                "😳",
                "Upgrades Abuse :(",
                "no more debug for u son",
                "80+ achievements?",
                "Hi, How are ya?",
                "i an no cair lol ez eL Le L lopllll",
                "Delta Timewall Gaming",
                "Let's do a little timewall",
                "Is this Omega Layers NG++?",
                "This mod has over 1e90 functions in it.",
                "Join the omega engine community server to talk with the modders",
                "you just got trolled",
                "That was easy",
                "xitov eyrlk kgfi wyy sz rcfip qslxe jox wyy byal",
                "new Decimal (Infinity) and Decimal.dInf aren't the same",
                "τ = 2π",
                "top news bottom news",
                "Its always the multipliers that makes your day good - Asher213",
                "@JeehanMoment",
                "Enhancers from The Prestige Tree????????",
                "We do a little of trolling",
                "how do i turn off news",
                "Don't mind me i'm just gonna leave you alone",
                "Unary > Binary - Unary Lover >:)",
                "when you break the 1st wall there will be the 2nd wall and when you break the 2nd wall there will be the 3rd wall and when you break the 3rd wall there will be the 4th wall and if you break the 4th wall you will gain a uncool title in JMMS server",
                "where's the 5th wall?",
                "bugs spotted",
                ".... ..",
                "A new challenger approaches!",
                "barely got easier",
                "unary approval",
                "what a scam",
                "what's so special about special elite?",
                "when you get softcapped",
                "once opon a time there was 5 news tickers but uh somehow 4 of them disappear and then there's 1 left the end",
                "wow that was pretty cool",
                "no way i broke function thingy again",
                "guys i just realised that when u get layer 1.8e308 in meta there is function thingy that allows you to inflate the game and btw thank you for listening to my spoiler now you know it oh and yeah i like sussy layers more than this :D",
                "i love tee - JeehanMoment",
                "THREE UPGRADES",
                "Jeehan Please stop adding more news ticker i'm dying...",
                "If Jeehan can make the timewalls shorter, can he made it longer?",
                "ν v",
                "Now make OLTW :troll:",
                "cool",
                "omega layers lore",
                "omega layers omega edition",
                "unoriginal game",
                "we do a little of coding *showing 100+ unicode stuffs*",
                "how to inflate your game in 3 days by JeehanMoment",
                "Screw Toxicity Become Acidity",
                "Ah yes, Time to Put 96 years timewall into my mod - JeehanCodder",
                "I like Bobm",
                "explosion",
                "You're gonna have a bad time balancing meta",
                "me when the me when uh i me virus me sus when impasta if the i forgor 💀",
                "i rember ッ",
                "i forgor 💀",
                "toxic >:/",
                "gotta leak leak leak",
                "when new stickb- oh wait wrong mod",
                "when news tick- oh wait wrong mod",
                "eg",
                "i",
                "guys",
                "agua",
                "Guys hear me out, I'm gonna (NaN)",
                "Omega Layers EZ aka Omega Layers but you having skill issue",
                "I found Mcdonald's IP adress it's 154.136.79.119",
                "Skill Issue",
                "Skill Tissue - JeehanMoment",
                "JeehanMoment more like JeehanModder",
                "how should i share my mod - JeehanMoment",
                "1 and l look the same in special e1ite fight me",
                "bugs report: restack achievements doesn't work properly",
                "Imagine seeing this news ticker",
                "I really like this mod every time i see my ee69.42 alfuh it makes me happy 10/10 please support JeehanMoment! Next time I'm gonna rate The Numbruh Tree.",
                "I really like the numbruh tree that made by JeehanMoment im actually impressed because i don't how he perfectly balance that game like most upgrades doesn't make sense so im confused anyways next time I'm gonna rate OLEZ",
                "abusing omega engine™",
                "*codes cutely*",
                "You committing 69 commits per second-",
                "what cand<strike>e</strike>ice - JeehanMoment",
                "how",
                "Why doesn't anyone play my mod i spent like 3 days to make all of this alone without any help, welp ig omega engine's help",
                "Yee",
                "this is epic",
                "Yees",
                "Jeehan is gone",
                "Focus on the next news ->",
                "what was the last news again?",
                "😳 Jeehan is Back 😳",
                "omega layers but you having timewall issues",
                "fake world record",
                "i aprove",
                "You Steal news ticker code from AD?!?",
                "Approved by Unary Master",
                "un-omega your layers",
                "here's my idea ->",
                "This mod isn't inspired by EX and NG+ mod i swear",
                "If Superspruce see this news, this news ticker will be deleted",
                "Is this game easier or harder",
                "The Number limit is above 10↑↑308, good luck!",
                "Maybe there are new News here? Nope, just the old news...",
                "ITS ABOUT THE METS-",
                "If you are going meta say goodbye to your progress you might regret doing it",
                "Ah yes my favourite thing to do modding a gaem",
                "Check out The Numbruh Tree or i'll steal your stuffs",
                "This mod isn't unbalanced you're just stu-",
                "My favourite shortcuts are CRTL+V, CRTL+C and shortcut to ur mo-",
                "I'm still stuck at Layer 69 - JeehanMoment",
                "I'm stuck at Layer 69 - Jeehan2561",
                "i can't even play OL EZ - JeehanModder",
                "Hi chat",
                "WAOW",
                "me when",
                "oh nu ninth generator exists o_O",
                "hardcapped",
                "this mod will be updated in november - JeehanMoment",
                "METa",
                "It's about the METa",
                "ඞ",
                "this is the worst news ticker in the game",
                "<a href='https://jwklong.github.io/Incremental-Snake'>click to play jwklong's incremental snek game</a>",
                "<a href='https://raw.githack.com/jeehan2561/The-Modding-Tree/master/index.html'>click to play the numbruh tree</a>",
                "<a href='https://discord.gg/ccbBZHYsTv'>Jeehan's Discord Server</a>",
                "ζ is Fake News!",
                "<a href='https://www.youtube.com/watch?v=lEuvYJQ5vog'>how to beat any mario game in 5 hours (real!)</a>",
                "<a href='https://www.youtube.com/shorts/NTvXsdww_rk'>roblox ads be like</a>",
                "<a href='https://www.youtube.com/watch?v=dpMnWv8blRo'>how to drive a car easily (real!)</a>",
                "<a href='https://www.youtube.com/watch?v=ij9MkbMSSUk'>how to eat an egg (real!)</a>",
                "<a href='https://www.youtube.com/watch?v=LrL8_b3LZLM'>click to see someone that dead (real!)</a>",
                "<a href='https://www.youtube.com/watch?v=j9V78UbdzWI'>click to eat reese's puffs (real!)</a>",
                "<a href='https://www.youtube.com/watch?v=mNkyhYAwUQg'>click to see snas (real!)</a>",
                "<a href='https://www.youtube.com/watch?v=gub9x8fP6yw'>click to hear epic tune (real!)</a>",
                "<a href='https://www.youtube.com/watch?v=Tt7bzxurJ1I'>click to get a rickrolled (real!)</a>",
                "<a href='https://www.youtube.com/watch?v=JRHARtLZLk8'>click to get a stickbugged (real!)</a>",
                "<a href='https://www.youtube.com/watch?v=RvBwypGUkPo'>click to get a coconut malled (real!)</a>",
                "ew sticker",
                "im using break_eternity.js",
                "im using break_eternity.sb3",
                "This News is 1x rarer than other lol",
                "The code is definitely not messy",
                "Can we get 4.20e69 likes on this video?",
                "Super Idol 的笑容 都没你的甜 八月正午的阳光 都没你耀眼 热爱 105 °C 的你 滴滴清纯的蒸馏水",
                "@here",
                "What",
                "Wat",
                "Wot",
                "No",
                "But",
                "Wut",
                "Nu",
                "@everyone",
                "unsussy news",
                "In",
                "Woah crazy",
                "Every Incremental needs a News Ticker",
                "Hi YT",
                "100 isn't a lot >:c - JeehanMoment",
                "n0",
                "This is not meme generator",
                "When",
                "E",
                "In 30 mins™",
                "No u",
                "no",
                "nu (ν)",
                "There's a hidden font that isn't avaiable normally",
                "Nu (Ν)",
                "UwU",
                "I was stuck at layer 69 - Jeehan2550",
                "Where is Jeehan2561?",
                "Make sure to check out both discord servers",
                "Can we actually get some new News",
                "⬤",
                "Sheesh",
                "Lack of Lag",
                "wow a new update let's check it ou-",
                "Chesse",
                "Click here for Nothing :P",
                "What's make me a good modder? if i were a bad modder i wouldn't put this news into this mod.",
                "newsticker",
                "Good Game...",
                "⸮ti si derorrim ton si swen sihT",
                "Subscribe to jwklong now",
                "Meta is so cool.",
                "this is kinda underrated tbh",
                "Suggest more messages in the Discord!",
                "Join my discord server Join my discord server Join my discord server Join my discord server Join my discord server Join my discord server Join my discord server Join my discord server Join my discord server Join my discord server Join my discord server Join my discord server Join my discord server Join my discord server Join m- *muted*",
                "new sticker",
                "e - βσηκ",
                "(hardcapped)",
                "I don't understand this, I just like big numbers",
                "the symbol is too small!",
                "(softcapped)",
                "This news is softcapp-",
                "This news doesn't exists if you can see this news this that means Jeehan just made an error or you are just too special",
                "News Ticker? Cool.",
                "\"if you hit a wall, keep hitting\" -winston churchill",
                "(hardcapped)",
                "XD you just got (softcapped)",
                "(╯°□°）╯︵ ┻━┻   -   TableFlipper07",
                "Well, I guess this'll do it",
                Utils.createRandomWord(175) + " sorry i steal code from jwklong",
                Utils.createRandomWord(175) + " sorry i steal code from the sus gaem",
                `<span style="color: hsl(0, 100%, 50%)">R</span>`
                +` <span style="color: hsl(45, 100%, 50%)">A</span>`
                +` <span style="color: hsl(90, 100%, 50%)">I</span>`
                +` <span style="color: hsl(135, 100%, 50%)">N</span>`
                +` <span style="color: hsl(180, 100%, 50%)">B</span>`
                +` <span style="color: hsl(225, 100%, 50%)">O</span>`
                +` <span style="color: hsl(270, 100%, 50%)">W</span>`,
                "modding.net",
                "Behind you...",
                "BruhMoment",
                "layer name moment",
                "weird themes",
                "hey, you could make a mod out of this",
                "when the imp- oh wrong mod",
                "basically there is a thi- (softcapped)",
                "incremental thing i guess",
                "omega layers but steam engine",
                "mod.js: powering layers",
                "hamburger",
                "monke",
                "Gammaly does more than catch errors",
                "i need monkey but the k is silent",
                "Powered by RNG",
                "alpha layer [Beta]",
                "i ran out of words on my hard drive :(",
                "what if i told you that secret achievements are real",
                "omega layers 2, coming in 2048 years",
                "finally a major release",
                "Number Upgrades When?",
                "go visit omega layers ez and sussy layers 2",
                "join the community server",
                "content when",
                "omega engine v-1.0.0: we removed all the features that aren't the main game",
                () => {return "what if i tell you that OLEZ v."+mod.version+" is the last update for this mod"},
                () => {return "powered by omega engine v"+mod.engineVer},
                () => ["jwklong", "JeehanMoment", "TJC games", "jwkshort", "a thing", "Lun4-R"][(Math.random() * 5).toFixed(0)] + " is cool",
                () => "😳 olez v"+ (mod.version).toString() + " 😳",
                () => "is that " + "αβγδεζηθικλμνξοπρστυφχψωΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ"[(Math.random() * 47).toFixed(0)] + " from omega layers?",
                () =>
                {
                    let res = "";
                    for(let i = 0; i < Math.floor(Math.random() * 6) + 4; i++)
                    {
                        let seed = Date.now() + i;
                        res += Utils.createRandomWord(Math.floor(Math.random() * 10) + 4, seed) + " ";
                    }
                    return res + "-" + Utils.createRandomWord(Math.floor(Math.random() * 3) + 4, Date.now() + 20) + " " + Utils.createRandomWord(Math.floor(Math.random() * 3) + 4, Date.now() + 21);
                },
                () => `<a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank">get Layer ` + PrestigeLayer.getNameForLayer(game.metaLayer.active ? game.metaLayer.layer.add(1).floor() : game.layers.length) + ` now [working 2021]</a>`,
                () => "This Number is randomly generated -> " + Math.pow(10, Math.random() * 6.01).toFixed(2) +
                    ". If it's above 1 000 000, consider yourself lucky!",
                    () => functions.formatNumber(game.metaLayer.active ? game.metaLayer.getApproxAlpha() : game.layers[0].resource, 2, 0, 1e9) + " α? That's just a rookie number",
                    () => "Rookie number? That's just " + functions.formatNumber(game.metaLayer.active ? game.metaLayer.getApproxAlpha() : game.layers[0].resource, 2, 0, 1e9) + " α",
                    () => "Motto of the Day: " + Utils.getMOTD(),
                    () => "I have your IP adress it's " + (Math.random() * 255).toFixed(0) + "." + (Math.random() * 255).toFixed(0) + "." + (Math.random() * 255).toFixed(0) + "." + (Math.random() * 255).toFixed(0) + " =)"
            ],
            currentMessage: "",
            messageIndex: -1
        }
    },
    computed: {
        animationDuration: function()
        {
            return 10 + 0.1 * this.currentMessage.replace(/<.*?>/g, "").length;
        }
    },
    methods: {
        getMessage: function()
        {
            const arr = Array.from(this.messages);
            if(this.messageIndex !== -1)
            {
                arr.splice(this.messageIndex, 1);
            }
            const index = Math.floor(Math.random() * arr.length);
            this.messageIndex = index;
            const element = arr[index];
            this.currentMessage = typeof element === "string" ? element : element();
        }
    },
    mounted: function()
    {
        this.getMessage();
        this.$refs.message.onanimationiteration = e =>
        {
            const anim = this.$refs.message.style.animation.slice();
            this.getMessage();
            this.$refs.message.style.animation = "none";
            void this.$refs.message.offsetWidth; //very black magic
            this.$refs.message.style.animation = anim;
            Vue.nextTick(() =>
            {
                if(this.$refs.message.style.animationDuration === "")
                {
                    this.$refs.message.style.animationDuration = this.animationDuration + "s";
                }
            });
        };
    },
    template: `<div class="news-ticker">
    <span ref="message" :style="{'animation-duration': animationDuration + 's'}" v-html="currentMessage"></span>
</div>`
})